#!/usr/bin/env bash

return

#-----------------------------------------------------------------------------#
# This is just a simple example of how to define custom actions for certain   #
# files. In this case we copy the file ssh_config to ~/.ssh/config if it      #
# doesn't already exist instead of symlinking it. This can be useful if you   #
# need different ssh configs on different machines (most of us do), but       #
# want to keep a basic version with all your univeral options in version      #
# control for when you first setup a new system.                              #
#-----------------------------------------------------------------------------#

echo -e "\e[1;33mChecking ssh config.\e[m"

# Add grep patterns for the affected files to the
# IGNORE array, otherwise they'll get symlinked
# with everything else later on.
IGNORE+=('ssh_config')

if ! [ -f ~/.ssh/config ]
then
	echo "No ssh config found, installing base."
	cp $DIR/ssh_config ~/.ssh/config
fi
